sudo: required
language: python
python:
- '3.5'
install:
- pip install codecov coverage
deploy:
  provider: pypi
  user: Neabfi
  password:
    secure: hIqQdpIlRQ7o4EgVw9eENgEyP39QIM5Zc7QyyTkIoZOsbdoZo65cFk0GgYZb+ay2FyhPI0BlzSUETLkVMURYvuHQjylAJQZW76l92YgjvdBxaK6x8o0TY3qlMdnlLIV9ttpQ3+fKjE/BDHVw3/Wt6mFGtrFIiD0a3/Jl3/TYgWuATqkMw5Ga7uHmccVbz6KhH3htpj+RHOP2VFgzaKlelRXYk+jHEvc26zna3aVwnVLCqOmnMemNqNOizrpRo6RmEzt2YJUHG9xPuL1DO0NmXuLjlyNaKWmaAdUlpb2092EEw63fQD6I/StegCQa8PcmtzM8ChnxD/c628kB0/vlGOokjVNFtKjQd2Lycida2wTnvbWEeigd9yQ29pmUuSy62tFGQn4KjZIRnd8FvsUat1x+ZplLSXDOSpmYtOMKoAroWPt9dawTu2KYsU3l3LWGtDJpWon47ElOD2OMkFd4U/X5rVFIjx/LPVY0TblFavwhR6cUrybdPpwEiTwJgccbp6LdQNfWysiOmBPezsnd11KDuagyvpbaHWT6XzY2R4Le0jeQ69dnTBWOFoU3mTRWUz/gFOt92H7+PlXcN56xkiEXq0a973ClGDJeZLisCXIRqllYYpaF0ECeowyM/4U/a62tekGOn+SV9TcjAhjXZHtOLxs6f/YD2vzPIL53Y2s=
  on:
    branch: master
    tags: false
script:
- nosetests --with-coverage
after_success:
- bash <(curl -s https://codecov.io/bash)
